---
title: Bloom Toolkit
description: This is the main Bloom Toolkit
id: Bloom-Toolkit-E03_es
highlight: '#EF7145'
defaults:
  locale: es
  pagination: true
  swipe: false
  next: "Siguiente"
  canReview: true


