---
title: Bloom Toolkit
description: This is the main Bloom Toolkit
id: Bloom-Toolkit-E07
highlight: '#EF7145'

defaults:
  locale: es
  navigation: false
  prev: "Back"
  next: "Next"
  pointScale: 10
  passingGrade: 6

bank:
  YeiraLab: 5
  Report: "*"
