---
title: Bloom Toolkit
description: This is the main Bloom Toolkit
id: Bloom-Toolkit-E04_es
highlight: '#EF7145'
defaults:
  locale: es
  pagination: true
  swipe: false
  next: "Next"
  canReview: true


